### ISSUE TITLE
Изучить доску Kanban в Github

### ISSUE THREAD

**Issue by gri-gri** [gri-gri/digital_culture_project_team_1#2]
Она находится в папке Projects -> Learn More

**Comment by Martakor1** [comment]
Прочитал

**Comment by gri-gri** [comment]
Гайд по issues прочитал, но вот Learn More по поводу Project board всю не осилил - там слишком много, это справочник. Основные вещи я понял, так что свою часть issue выполнил.

**Comment by gri-gri** [comment]
Супер!
