### ISSUE TITLE
Решить архиважные концептуальные вопросы

### ISSUE THREAD

**Issue by gri-gri** [gri-gri/digital_culture_project_team_1#9]
Путём коллегиального решения предлагается решить несколько вопросов, возникших в процессе написания use-кейсов.
1. Будет ли введена авторизация учителя и ученика? 
     * Минусы авторизации: более сложная реализация, включая use-кейсы администратора. 
     * Минусы неавторизации: хаотичность в сфере авторства работ и поиска лабораторных.
2. Вопрос с дисциплинами.
       2.0 Существуют ли вообще дисциплины в нашей системе? То есть одно из свойств лабы.
       2.1 Может ли один практик принимать лабы по нескольким дисциплинам? 
       2.2 Будут ли показываться лабы студенту сразу всем списком доступных или сначала по дисциплинам? 
3. Можно ли сдавать лабы несколько раз?
4. Сдать лабу можно только в формате файла или дополнительные форматы ответа, как на сайте по линалу, например?
5. Будут ли лабы показываться сразу после создания или студентам будут видны не сразу? Если не сразу, то они будут открываться вручную или по дате?
6. Будут ли дедлайны? Если да, то хард (после которых программно нельзя отправить лабу) или софт? 

Ожидается, что вы все ответите на эти вопросы, чтобы мы коллегиально это решили и смогли доделать use-кейсы.

**Comment by gri-gri** [comment]
Моё мнение:
1. Да, я считаю, что, конечно, нужна авторизация. Это просто неправильно в 21 веке не делать авторизацию, плюс иначе реально будет хаос.
2. Да, я считаю, дисциплины должны быть. Наверное, не следует одному преподу давать несколько дисциплин и в случае чего можно несколько раз зарегаться, по типу: "Хвост А.П. (программирование)" и "Хвост А.П. (Алгоритмы)". А студенту должны показываться лабы по дисциплинам, иначе это будет слишком много лаб. Впрочем, это можно сделать в виде раскрывающегося дерева, так что всё искать можно будет быстро.
3. Да, я считаю лабы можно сдавать несколько раз. Опционально, если будет время, можно будет сделать возможность ограничения по количеству отправлений.
4. Думаю, сначала нужно сделать только в формате файла. Опционально, сделать дополнительные форматы ответа.
5. Мне кажется, сначала нужно сделать, что лабы будут открываться только вручную преподавателем. Опционально, сделать открытие по дате.
6. Да, думаю сначала стоит сделать хард дедлайны. Опционально, сделать софт дедлайны.

**Comment by dobrmar** [comment]
2. Мне кажется, не нужно? Можно вместо дисциплин указывать ФИО преподавателя, которому сдается лаба. Тогда и каждому преподу будут показываться только его лабы, и вопрос про несколько дисциплин отпадает.
3. Можно реализовать систему: сдал лабу - ждешь проверки - если препод отправил на доработку, можешь сдать еще раз.
По остальным такое же мнение.

**Comment by Martakor1** [comment]
1. Окей, пусть будет авторизация. Это ради пункта 3 о пересдаче лаб.
2. На данном этапе не понятно. Но лучше бы если бы они просто все подряд высвечивались и всё. И сами сортировались сразу по дате, чтобы первые были самыми актуальными. Регать учителя на два разных предмета, как на два пользователя - не очень. В общем решим потом.
3. Окей
4. Ну конечно в формате файла. Не текст же писать в поле. А форматов не напасёшься, это же не сайт только с матрицами.
5. А разве нельзя, чтобы все были видны? Ну ладно, можно просто у препода добавить функцию отложенного выкладывания.
6. Хард. Софт мы не сделаем, так как софт влияет на оценку, а не на доступ к лабе.

**Comment by gri-gri** [comment]
2, 5. Смотрите, почему я говорю про дисциплины и про отложенное выкладывание. Во-первых, если связывать лабы с ФИО преподавателя, это, конечно, возымеет положительный эффект в виде запоминания ФИО у учеников, однако всё же получается лишнее действие. Вы же, когда ищете сайт, например, geolin, вы же идёте делать **линал**, а не **задание Москаленко М.А.** Во-вторых, если практик будет открывать все лабы сразу (называться они зачастую будут, несложно предположить, "Лаба 1", "Лаба 2" и т.д.) и не разделять по дисциплинам, то это будет непонятный длинный список. Сравните:
> Текущие лабы:
> * Лаба 3
> * Сделать uint_1024
> * Лаба 2
> * Д/з 5
> * Домашнее задание по ФСР

И это:
> Текущие лабы:
> * ЭВМ:
>     * Лаба 3
>     * Лаба 2
> * Программирование:
>     * Сделать uint_1024
> * Линейная алгебра:
>     * Домашнее задание по ФСР
> * Математический анализ:
>     * Д/з 5

Или что-нибудь подобное, в таком виде.

3. Хм, а идея "не более одной незакрытой лабосдачи" мне нравится.
4. Окей, только в формате файлов, согласен.
6. Софт можно будет, если захотим, опционально в формате огромной красной плашки "отправлено позже софт дедлайна" около лабосдачи.

**Comment by dobrmar** [comment]
2. Окей, можно в сценарий создания лаб добавить пункт "Выбрать предмет". Так и у учеников список будет нормальный, и  "несколько дисциплин у одного практика" реализуется. Дополнительно можно будет сделать проверку, действительно ли этот практик ведет этот предмет у этой группы (либо просто выпадающий список сделать только с подходящими дисциплинами)

**Comment by schtschee** [comment]
1,Точно да, должна быть.
2. Думаю, дисциплины нужны. Мне понравилась идея с "выбрать предмет" при создании/просмотре лабы - это удобно со стороны препода. А со стороны студента можно просто сортировку по дисциплинам и по дате создания/дедлайна сделать.
3.  Согласна с тем, что предлагали.
4. Чисто файл.
5. Вроде открытие вручную самый норм вариант. Ну и опционально добавить отложенное выкладывание.
6. Я за хард дедлайны. Софт. если нужны будут, можно в виде "предупреждения" или "красного флажка" сделать, как предлагали.

**Comment by gri-gri** [comment]
Отлично, всем спасибо!
